services:
  postgres:
    image: postgres
    container_name: postgres_pagamentos
    restart: always
    environment:
      POSTGRES_DB: pagamentos
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: